Improve documentation in config.h (NFC)
google/mt pull request #4
Opened 2017-04-23 17:06 UTC by sam-mccall

Adjusted comments that were missing, poorly worded, overly obscure, or
otherwise unhelpful to users. Some research was required!

Removed macros that were unused/trivially used.

Switched /* C comments */ to // line-comments.

Resisted the urge to reorder, rename, and remove options, to keep the
diff small.

2017-04-23 21:15 UTC, chandlerc requested changes
Awesome, one question below.

2017-04-23 21:15 UTC, chandlerc commented on config.h
> +//   2 : only match if mode is active AND numlock was toggled off.
Isn't 2 triggered when numlock is *on*? Maybe I misread that code.

2017-04-23 22:05 UTC, sam-mccall commented on config.h
> +//   2 : only match if mode is active AND numlock was toggled off.
That's what the old comment said, but in the `kmap()` loop:
```
if (term.numlock && kp->appkey == 2)
      continue;
```
So if `numlock` is 1, then we *skip* rules with `appkey==2`

Maybe `numlock=1` means *off* and 0 means *on*?

Looking at where this was added in 172f65436ce14a52842d67b862fdc45f8ff3ada3, my interpretation is:
  - this changed the default from generating dedicated escape sequences for `XK_KP_2` and friends, to just generating `2`
  - it seems reasonable to call the new mode numlock, and indeed it was indicated by `numlock=1`
  - so the old comment is wrong and the new one is correct
  - but I have very little confidence the behavior is actually good, worth checking what other terms, apps, tmux think about these keys

2017-09-24 19:50 UTC, chandlerc commented on config.h
> +//   2 : only match if mode is active AND numlock was toggled off.
Wow. Agree that this is an improvement in accuracy, and that we should figure out what is "right" here...

2017-09-24 19:51 UTC, chandlerc approved these changes
Finally back to this, LGTM, merging. Thanks!

2017-09-24 19:51 UTC, merged